chore: add test coverage threshold (#8)
* chore: add test coverage threshold

* chore(ci): separate test cover check script

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -2,6 +2,9 @@
 
 version: "3"
 
+env:
+  TEST_COVERAGE_THRESHOLD: 90
+
 tasks:
   clean:
     desc: Clean
@@ -55,7 +58,7 @@ tasks:
     deps:
       - test:clean
     cmds:
-      - go test -race -v  ./...
+      - go test -race ./...
 
   test:cover:
     desc: Run tests with coverage
@@ -66,6 +69,25 @@ tasks:
     desc: Run tests with coverage profile
     cmds:
       - go test ./... -coverprofile=coverage.out
+      - go tool cover -func coverage.out
+
+  test:cover:check:
+    desc: Check test coverage
+    deps:
+      - test:coverprofile
+    cmds:
+      - |
+        echo "Checking test coverage is above threshold ..."
+        echo "Threshold             : $TEST_COVERAGE_THRESHOLD %"
+        totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+        echo "Current test coverage : $totalCoverage %"
+        if (( $(echo "$totalCoverage $TEST_COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+            echo "OK"
+        else
+            echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+            echo "Failed"
+            exit 1
+        fi
 
   test:cover:report:
     desc: Show coverage
@@ -91,4 +113,5 @@ tasks:
     cmds:
       - task: build
       - task: lint
-      - task: test:coverprofile
+      - task: test:race
+      - task: test:cover:check
